# docker/docker-compose.spark.yml
services:
  spark-master:
    image: apache/spark:4.1.0-preview3-python3
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8088
    ports:
      - "7077:7077"
      - "8088:8088"
    networks:
      - mlops

  spark-worker-1:
    image: apache/spark:4.1.0-preview3-python3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --webui-port 8089
    networks:
      - mlops

networks:
  mlops:
    external: true