# docker/docker-compose.spark.yml
services:
  spark-master:
    image: bitnami/spark:3.5
    container_name: mlops-spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - mlops

  spark-worker-1:
    image: bitnami/spark:3.5
    container_name: mlops-spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - mlops

networks:
  mlops:
    external: true